fun main() {
    throw Exception(UnknownError())
// Write some code to cause an exception
}